/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNews: typeof import('./src/views/addNews.vue')['default']
    AllNews: typeof import('./src/views/allNews.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Btn: typeof import('./src/components/form/btn.vue')['default']
    Checkbox: typeof import('./src/components/form/checkbox.vue')['default']
    FormMain: typeof import('./src/components/form/formMain.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/form/input.vue')['default']
    Modal: typeof import('./src/components/posts/modal.vue')['default']
    Nav: typeof import('./src/components/nav/nav.vue')['default']
    New: typeof import('./src/components/new.vue')['default']
    Overlay: typeof import('./src/components/posts/overlay.vue')['default']
    Posts: typeof import('./src/components/posts/posts.vue')['default']
    Preloader: typeof import('./src/components/preloader/preloader.vue')['default']
    Profile: typeof import('./src/components/profile/profile.vue')['default']
    ProfileEmail: typeof import('./src/components/profile/profileEmail.vue')['default']
    ProfileImg: typeof import('./src/components/profile/profileImg.vue')['default']
    ProfileName: typeof import('./src/components/profile/profileName.vue')['default']
    Radio: typeof import('./src/components/form/radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./src/components/form/textarea.vue')['default']
    TheTest: typeof import('./src/components/TheTest.vue')['default']
    TheTestNew: typeof import('./src/components/TheTestNew.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
